version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    # ビルドするDockerfileの指定
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    # 環境変数を設定(.envに紐づく)
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  web:
    # Nginxのバージョンを指定
    image: nginx:1.18
    # ビルドするDockerfileを指定
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    # コンテナ間のポート番号の対応づけを設定{ローカル}:{Dockerコンテナ}
    ports:
      - ${WEB_PORT}:80
    # コンテナ間の依存関係を設定。PHP→Nginxの順番でコンテナを起動する（appはPHPのDockerコンテナを指している）
    depends_on:
      - app
    volumes:
      # ローカルとDockerコンテナ間のディレクトリ・ファイル等のリソースを関連付する設定(ローカルのリソース:Dockerコンテナ内のリソース）
      - ./src/:/var/www/html
      # 画像を表示させるためのシンボリックを貼る
      # - ./src/storage/app/public/images/:/var/www/html/public/storage/images
      # - ./src/storage/app/public/images/:/var/www/html/storage/app/public/images

  db:
    image: mysql:5.7
    # ビルドするDockerfileの指定
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    # ローカルのポート番号
    ports:
      - ${DB_PORT}:3306
    # MySQLの環境変数
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    links:
      - db:mysql
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025