version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
    working_directory: src
    steps:
      - checkout
      - restore_cache:
          key: composer-v2-{{ checksum "src/composer.lock" }}
      - run:
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v2-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor 
      - restore_cache:
          key: npm-v2-{{ checksum "src/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v2-{{ checksum "src/package-lock.json" }}
          paths:
            - src/node_modules
      - run:
          command: npm run dev
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit