version: 2.1
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/php:7.3-node-browsers
    #   - image: circleci/postgres:11.6-alpine
    #     environment:
    #       POSTGRES_DB: larasns
    #       POSTGRES_USER: default
    #       POSTGRES_PASSWORD: secret
    # environment:
    #   APP_ENV: testing
    #   DB_CONNECTION: mysql
    #   DB_HOST: localhost
    #   DB_PORT: 5432
    #   DB_DATABASE: larasns
    #   DB_USERNAME: default
    #   DB_PASSWORD: secret
    steps:
      - checkout
      - restore_cache:
          key: composer-v2-{{ checksum "src/composer.lock" }}
      - run:
          working_directory: src
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v2-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor 
      - restore_cache:
          key: npm-v2-{{ checksum "src/package-lock.json" }}
      - run:
          working_directory: src
          name: npm ci
          # node_modulesが存在していない場合はnpm ciを実行する
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v2-{{ checksum "src/package-lock.json" }}
          paths:
            - $HOME/.npm
            # - src/node_modules
      - run:
          working_directory: src
          command: npm run dev
      # - run: php ./src/artisan --env=testing
      # - run: php ./src/vendor/bin/phpunit --configuration=./src/phpunit.xml
      - run:
          working_directory: src
          name: php test
          command: vendor/bin/phpunit tests

      # - run: php ./src/artisan --env=testing
      # - run: php ./src/vendor/bin/phpunit --configuration=./src/phpunit.xml
      # - run:
      #     working_directory: src
      #     name: php test
      #     command: vendor/bin/phpunit
