version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./src/composer.lock" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist --working-dir=./src/composer.lock
      - save_cache:
          key: v1-dependencies-{{ checksum "./src/composer.lock" }}
          paths:
            - ./src/vendor      
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit