version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: composer-v2-{{ checksum "src/composer.lock" }}
      - run:
          working_directory: src
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v2-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor 
      - restore_cache:
          key: npm-v2-{{ checksum "src/package-lock.json" }}
      - run:
          working_directory: src
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v2-{{ checksum "src/package-lock.json" }}
          paths:
            - src/node_modules
      - run:
          working_directory: src
          command: npm run dev
      # - run: php ./src/artisan --env=testing
      # - run: php ./src/vendor/bin/phpunit --configuration=./src/phpunit.xml
      - run:
          working_directory: src
          name: php test
          command: ./src/vendor/bin/phpunit --configuration=./src/phpunit.xml

      # - run: php ./src/artisan --env=testing
      # - run: php ./src/vendor/bin/phpunit --configuration=./src/phpunit.xml
      # - run:
      #     working_directory: src
      #     name: php test
      #     command: vendor/bin/phpunit