version: 0.0
os: linux
files:
  - source: /
    destination: /home/webapp/spoily-ci

permissions:
  - object: /home/webapp/spoily-ci
    owner: webapp
    group: webapp

hooks:
  AfterInstall:
    - location: /scripts/after_install.sh
      timeout: 60
      runas: webapp